global:
  scrape_interval: 15s # Cứ 15 giây đi thu thập dữ liệu 1 lần
  evaluation_interval: 15s

scrape_configs:
  # Tự giám sát chính nó
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Giám sát RAM, CPU của toàn bộ Docker Container qua cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']