FROM apache/spark:3.5.1-scala2.12-java11-python3-r-ubuntu

USER root

# Cài đặt pip và các thư viện cần thiết cho Python
RUN apt-get update && apt-get install -y python3-pip && \
    pip3 install --no-cache-dir pydantic-settings python-dotenv && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY jars/* /opt/spark/jars/
RUN chmod 644 /opt/spark/jars/*.jar

USER spark
